[build]
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"
  publish = "frontend/adcore-payments-ui/dist/adcore-payments-ui"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
