[build]
  base = "frontend/adcore-payments-ui"
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"
  publish = "dist/adcore-payments-ui/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
